### PR TITLE
Added a python file to export a csv from the database

### PR DESCRIPTION
**Pull request by adamsong**
For the teams who would like this data as a spreadsheet this script will dump the matches table as a csv to stdout.

### CODE REVIEW

**Comment by vampjaz** [comment]
I'll merge this tomorrow when I push some of my local changes.

**Comment by ArchdukeTim** [comment]
Why not print to a csv file?

**Comment by vampjaz** [comment]
Here's an idea for more concise code that does print to a csv:

``` python
import os,sys,sqlite3
from config import *

conn = sqlite3.connect(DATABASE)
c = conn.cursor()
fd = open('data_dump.csv')

print ','.join(row[1] for row in c.execute('PRAGMA table_info(matches)'))
fd.write(','.join(row[1] for row in c.execute('PRAGMA table_info(matches)')) + '\n')

for row in c.execute('SELECT * FROM matches'):
    print ','.join(row)
    fd.write(','.join(row) + '\n')

fd.close()
```

**Comment by ArchdukeTim** [comment]
pls merge. Kinda want this

**Pull request merged**
